- name: Run the preparation steps
  hosts: all
  become: true
  roles:
    - preparation

- name: Run the Docker role
  hosts: all
  become: true
  roles:
    - docker

- name: Run the Zsh role
  hosts: all
  roles:
    - zsh

- name: Run the Git role
  hosts: all
  roles:
    - git
