---

- name: Create default-python-packages symlink
  ansible.builtin.file:
    src: "~{{ user.username }}/.dotfiles/roles/python/files/default-python-packages"
    dest: "~{{ user.username }}/.default-python-packages"
    state: link
  become: true

- name: Install ipython
  ansible.builtin.apt:
    package: python3-ipython
  become: true

# - name: Create ipython.py symlink
#   ansible.builtin.file:
#     src: "~{{ user.username }}/.dotfiles/roles/python/files/ipython.py"
#     dest: "~{{ user.username }}/.ipython/profile_default/ipython_config.py"
#     state: link
#   become: true